"""
inference/prompt_builder.py — Builds structured prompts for the inference pipeline.

Responsible for:
1. Constructing the full chat-formatted prompt from an alert dict.
2. Applying the system prompt and user message using Phi-3 instruct format.
3. Staying strictly decoupled from model loading (no torch imports here).
"""

import json
import logging

from config import SYSTEM_PROMPT

logger = logging.getLogger(__name__)


def build_inference_prompt(alert: dict) -> str:
    """
    Build the full Phi-3 instruct formatted prompt for inference.

    The prompt ends with '<|assistant|>' to prime the model to generate
    the JSON completion — we do NOT include the assistant's response.

    Args:
        alert: Validated alert dict conforming to input_schema.json.

    Returns:
        A formatted string ready to pass to the tokenizer.
    """
    alert_json_str = json.dumps(alert, indent=2)

    user_message = (
        "Analyze the following normalized security alert and respond with a valid "
        "MLReasoningResult JSON object. Output ONLY the JSON with no surrounding text:\n\n"
        f"```json\n{alert_json_str}\n```"
    )

    prompt = (
        f"<|system|>\n{SYSTEM_PROMPT}<|end|>\n"
        f"<|user|>\n{user_message}<|end|>\n"
        f"<|assistant|>\n"
    )

    logger.debug(f"Built prompt for alert_id={alert.get('alert_id', 'unknown')}")
    return prompt


def extract_json_from_response(raw_response: str) -> str:
    """
    Extract the JSON substring from the raw model output.

    Phi-3 may include trailing <|end|> tokens or whitespace after the JSON.
    This function strips those artifacts and returns clean JSON text.

    Args:
        raw_response: The raw string generated by the model.

    Returns:
        A clean JSON string ready for json.loads().

    Raises:
        ValueError: If no valid JSON object is found in the response.
    """
    # Strip Phi-3 end tokens
    response = raw_response.strip()
    for end_token in ["<|end|>", "<|endoftext|>", "</s>"]:
        response = response.split(end_token)[0].strip()

    # Find the first '{' and last '}' to extract the JSON block
    start = response.find("{")
    end = response.rfind("}")

    if start == -1 or end == -1 or end <= start:
        raise ValueError(
            f"No valid JSON object found in model response. "
            f"Raw output (first 300 chars): {raw_response[:300]}"
        )

    json_str = response[start : end + 1]

    # Quick sanity check — will raise json.JSONDecodeError if malformed
    try:
        json.loads(json_str)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Model output contains malformed JSON: {e}. "
            f"Extracted string: {json_str[:300]}"
        )

    return json_str
