"""
inference/prompt_builder.py — Builds structured prompts for the inference pipeline.

Responsible for:
1. Constructing the full chat-formatted prompt from an alert dict.
2. Applying the system prompt and user message using Phi-3 instruct format.
3. Staying strictly decoupled from model loading (no torch imports here).
"""

import json
import logging

from config import SYSTEM_PROMPT

logger = logging.getLogger(__name__)


def build_inference_prompt(alert: dict) -> str:
    """
    Build the full Phi-3 instruct formatted prompt for inference.

    The prompt ends with '<|assistant|>' to prime the model to generate
    the JSON completion — we do NOT include the assistant's response.

    Args:
        alert: Validated alert dict conforming to input_schema.json.

    Returns:
        A formatted string ready to pass to the tokenizer.
    """
    alert_json_str = json.dumps(alert, indent=2)

    # No markdown fences — Phi-3 interprets ```json blocks as documentation
    # and responds with prose. Plain text forces a direct completion.
    user_message = (
        "Classify this security alert. "
        'Reply with ONLY a JSON object in this exact format — no other text:\n'
        '{"attack_type_confirmed": "<label>", "confidence_score": <0.0-1.0>}\n\n'
        f"Alert:\n{alert_json_str}"
    )

    prompt = (
        f"<|system|>\n{SYSTEM_PROMPT}<|end|>\n"
        f"<|user|>\n{user_message}<|end|>\n"
        f"<|assistant|>\n"
        '{"attack_type_confirmed": "'  # Hard-prefix: model must continue the JSON
    )

    logger.debug(f"Built prompt for alert_id={alert.get('alert_id', 'unknown')}")
    return prompt


def extract_json_from_response(raw_response: str, fallback_on_error: bool = True) -> str:
    """
    Extract the JSON substring from the raw model output.

    Because build_inference_prompt injects a hard-prefix of
    '{"attack_type_confirmed": "' into the assistant turn, the raw_response
    from the model is only the *continuation* (e.g. 'brute_force", ...}').
    This function reconstructs the full JSON string before parsing.

    Args:
        raw_response:     The raw string generated by the model.
        fallback_on_error: If True (default), return a safe '{"attack_type_confirmed":
                          "unknown", "confidence_score": 0.0}' string on any
                          parse failure instead of raising.  Set False in tests
                          where you want hard failures.

    Returns:
        A clean JSON string ready for json.loads().

    Raises:
        ValueError: If fallback_on_error is False and no valid JSON is found.
    """
    FALLBACK = '{"attack_type_confirmed": "unknown", "confidence_score": 0.0}'
    # The hard-prefix injected into the prompt — must match build_inference_prompt exactly
    HARD_PREFIX = '{"attack_type_confirmed": "'

    # Strip Phi-3 end tokens
    response = raw_response.strip()
    for end_token in ["<|end|>", "<|endoftext|>", "</s>"]:
        response = response.split(end_token)[0].strip()

    # Re-attach the hard-prefix that was in the prompt (not echoed by the model)
    if not response.startswith("{"):
        response = HARD_PREFIX + response

    # Find the first '{' and last '}' to extract the JSON block
    start = response.find("{")
    end = response.rfind("}")

    if start == -1 or end == -1 or end <= start:
        msg = (
            f"No valid JSON object found in model response. "
            f"Raw output (first 300 chars): {raw_response[:300]}"
        )
        if fallback_on_error:
            logger.warning(msg + " — using fallback label 'unknown'")
            return FALLBACK
        raise ValueError(msg)

    json_str = response[start : end + 1]

    try:
        json.loads(json_str)
    except json.JSONDecodeError as e:
        msg = (
            f"Model output contains malformed JSON: {e}. "
            f"Extracted string: {json_str[:300]}"
        )
        if fallback_on_error:
            logger.warning(msg + " — using fallback label 'unknown'")
            return FALLBACK
        raise ValueError(msg)

    return json_str
